name: SonarCloud

on:
    push:
        branches:
            - "**" # Analisa todas as branches
    pull_request:
        branches:
            - "**"

jobs:
    build:
        name: Build and analyze
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: "17"

            - name: Cache SonarCloud packages
              uses: actions/cache@v3
              with:
                  path: ~/.sonar/cache
                  key: ${{ runner.os }}-sonar-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-sonar-

            - name: Build with Gradle
              run: ./gradlew build

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@v1
              with:
                  args: sonar-scanner
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
